# Generated by Django 4.2.7 on 2025-11-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_classgroup_room_classgroup_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per student for this class', max_digits=10, verbose_name='Cost'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Assigned Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.classgroup', verbose_name='Class Group')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.homework', verbose_name='Homework')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'ordering': ['-submitted_at', 'student'],
                'indexes': [models.Index(fields=['homework', 'student'], name='core_homewo_homewor_95fdd0_idx'), models.Index(fields=['is_completed'], name='core_homewo_is_comp_365ff2_idx')],
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['class_group', 'due_date'], name='core_homewo_class_g_120eaa_idx'),
        ),
    ]
