# Generated by Django 4.2.7 on 2025-11-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classgroup_cost_homework_homeworksubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/assignments/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/submissions/', verbose_name='Submission File'),
        ),
    ]
