# Generated by Django 4.2.7 on 2025-11-30 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homework_file_homeworksubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Admin who owns this center (for tenant isolation)', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_centers', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['owner'], name='core_center_owner_i_ac0250_idx'),
        ),
    ]
