# Generated by Django 4.2.7 on 2025-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_center_owner_center_core_center_owner_i_ac0250_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='max_points',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum points for this homework', max_digits=6, verbose_name='Max Points'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score given by teacher (out of homework max_points)', max_digits=6, null=True, verbose_name='Score'),
        ),
    ]
